### PR TITLE
Wrap panic messages at the terminal width

### LINKED ISSUE #140: `tparse` outputs a lot of trailing spaces when tests panic with a long message
## What

When `tparse` receives a JSON result of tests panicked with a long message, its output has a lot of trailing spaces. They make the output hard to read when the terminal is configured to soft-wrap long lines.

## Repro Steps

1. Create `main_test.go` below. Its test panics with a long message.

```go
package main_test

import (
    "testing"
)

func TestFoo(t *testing.T) {
    panic("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat. Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam pharetra risus eu ipsum euismod gravida.")
}
```

2. Run the test and pass the result JSON to `tparse`.

```sh
go test -json main_test.go | tparse
```

## Actual

The output has a lot of trailing spaces. It's hard to read when the terminal is configured to soft-wrap long lines. You can select-all the output below to visualize trailing spaces.

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
┃   PANIC  package: command-line-arguments • TestFoo   ┃                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat. Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam pharetra risus eu ipsum euismod gravida. [recovered]
	panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat. Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam pharetra risus eu ipsum euismod gravida.            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
goroutine 18 [running]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
testing.tRunner.func1.2({0x140660, 0x1a8aa0})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1734 +0x1ac                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
testing.tRunner.func1()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1737 +0x334                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
panic({0x140660?, 0x1a8aa0?})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/runtime/panic.go:787 +0x124                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
command-line-arguments_test.TestFoo(0x400008a700?)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
	/home/vscode/go-long-fail-test/main_test.go:8 +0x2c                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
testing.tRunner(0x400008a700, 0x17d1c0)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1792 +0xe4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
created by testing.(*T).Run in goroutine 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1851 +0x374                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
FAIL	command-line-arguments	0.005s                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
┌──────────────────────────────────────────────────────────────────────────┐
│  STATUS │ ELAPSED │        PACKAGE         │ COVER │ PASS │ FAIL │ SKIP  │
│─────────┼─────────┼────────────────────────┼───────┼──────┼──────┼───────│
│  PANIC  │  0.00s  │ command-line-arguments │  --   │  --  │  --  │  --   │
└──────────────────────────────────────────────────────────────────────────┘
```

## Expected

The output has no trailing space, as shown in an example below.

## Workaround

I can pipe the `tparse` output to `sed 's/\s\+$//g'` to trim trailing spaces.

```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃   PANIC  package: command-line-arguments • TestFoo   ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat. Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam pharetra risus eu ipsum euismod gravida. [recovered]
	panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat. Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam pharetra risus eu ipsum euismod gravida.

goroutine 18 [running]:
testing.tRunner.func1.2({0x140660, 0x1a8aa0})
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1734 +0x1ac
testing.tRunner.func1()
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1737 +0x334
panic({0x140660?, 0x1a8aa0?})
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/runtime/panic.go:787 +0x124
command-line-arguments_test.TestFoo(0x400008a700?)
	/home/vscode/go-long-fail-test/main_test.go:8 +0x2c
testing.tRunner(0x400008a700, 0x17d1c0)
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1792 +0xe4
created by testing.(*T).Run in goroutine 1
	/home/vscode/.asdf/installs/golang/1.24.0/go/src/testing/testing.go:1851 +0x374
FAIL	command-line-arguments	0.005s

┌──────────────────────────────────────────────────────────────────────────┐
│  STATUS │ ELAPSED │        PACKAGE         │ COVER │ PASS │ FAIL │ SKIP  │
│─────────┼─────────┼────────────────────────┼───────┼──────┼──────┼───────│
│  PANIC  │  0.00s  │ command-line-arguments │  --   │  --  │  --  │  --   │
└──────────────────────────────────────────────────────────────────────────┘
```

### PR DESCRIPTION
**Pull request by masaru-iritani**
## What

Wrap the panic message at the terminal width.

## Why

Closes #140

## How Tested

`tparse` output is wrapped at 80 characters when the terminal width is 80 characters.

```
$ echo $COLUMNS
80

$ go run . -file ./test.jsonl
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                  
┃   PANIC  package: command-line-arguments • TestLongPanic   ┃                  
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                  
panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui      
maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar   
lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare      
egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque   
pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat.   
Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor    
fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam     
pharetra risus eu ipsum euismod gravida. [recovered]                            
    panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui  
maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar   
lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare      
egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque   
pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat.   
Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor    
fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam     
pharetra risus eu ipsum euismod gravida.                                        
                                                                                
goroutine 21 [running]:                                                         
testing.tRunner.func1.2({0x629aa0, 0x6d5410})                                   
    /usr/local/go/src/testing/testing.go:1734 +0x21c                            
testing.tRunner.func1()                                                         
    /usr/local/go/src/testing/testing.go:1737 +0x35e                            
panic({0x629aa0?, 0x6d5410?})                                                   
    /usr/local/go/src/runtime/panic.go:792 +0x132                               
command-line-arguments.TestLongPanic(0xc00008efc0?)                             
    /workspaces/tparse/tests/panic_test.go:98 +0x26                             
testing.tRunner(0xc00008efc0, 0x691ae8)                                         
    /usr/local/go/src/testing/testing.go:1792 +0xf4                             
created by testing.(*T).Run in goroutine 1                                      
    /usr/local/go/src/testing/testing.go:1851 +0x413                            
FAIL    command-line-arguments    0.006s                                        
                                                                                
╭────────┬─────────┬────────────────────────┬───────┬──────┬──────┬──────╮
│ Status │ Elapsed │        Package         │ Cover │ Pass │ Fail │ Skip │
├────────┼─────────┼────────────────────────┼───────┼──────┼──────┼──────┤
│ PANIC  │  0.00s  │ command-line-arguments │  --   │  --  │  --  │  --  │
╰────────┴─────────┴────────────────────────┴───────┴──────┴──────┴──────╯
exit status 1
```

## Ref

The latest version without this change outputs a lot of trailing spaces which result in a lot of blank lines.

```
$ go run github.com/mfridman/tparse@latest -file ./test.jsonl
go: downloading github.com/mfridman/tparse v0.17.0
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
┃   PANIC  package: command-line-arguments • TestLongPanic   ┃                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat. Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam pharetra risus eu ipsum euismod gravida. [recovered]
        panic: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed in dui maximus, finibus arcu in, ornare justo. Nullam at velit ullamcorper, pulvinar lectus nec, volutpat sem. Aliquam lacus risus, porta nec erat quis, ornare egestas risus. Sed ut mi dignissim, molestie nisl ac, vehicula risus. Quisque pretium efficitur scelerisque. Aenean tincidunt erat et sollicitudin feugiat. Donec fermentum urna mollis molestie volutpat. In lacinia auctor enim auctor fringilla. Nunc id elit vitae magna consectetur finibus id et lacus. Nullam pharetra risus eu ipsum euismod gravida.            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
goroutine 21 [running]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
testing.tRunner.func1.2({0x629aa0, 0x6d5410})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        /usr/local/go/src/testing/testing.go:1734 +0x21c                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
testing.tRunner.func1()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        /usr/local/go/src/testing/testing.go:1737 +0x35e                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
panic({0x629aa0?, 0x6d5410?})                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        /usr/local/go/src/runtime/panic.go:792 +0x132                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
command-line-arguments.TestLongPanic(0xc00008efc0?)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
        /workspaces/tparse/tests/panic_test.go:98 +0x26                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
testing.tRunner(0xc00008efc0, 0x691ae8)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        /usr/local/go/src/testing/testing.go:1792 +0xf4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
created by testing.(*T).Run in goroutine 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        /usr/local/go/src/testing/testing.go:1851 +0x413                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
FAIL    command-line-arguments  0.006s                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
╭────────┬─────────┬────────────────────────┬───────┬──────┬──────┬──────╮
│ Status │ Elapsed │        Package         │ Cover │ Pass │ Fail │ Skip │
├────────┼─────────┼────────────────────────┼───────┼──────┼──────┼──────┤
│ PANIC  │  0.00s  │ command-line-arguments │  --   │  --  │  --  │  --  │
╰────────┴─────────┴────────────────────────┴───────┴──────┴──────┴──────╯
exit status 1
```

### CODE REVIEW

File: internal/app/table_failed.go [hunk 1]
```diff
@@ -114,7 +115,12 @@ func (c *consoleWriter) prepareStyledPanic(
 		}
 		rows.WriteString(e.Output)
 	}
-	return lipgloss.JoinVertical(lipgloss.Left, styledPackageHeader, rows.String())
+	width, _, err := term.GetSize(int(os.Stdout.Fd()))
+	if err != nil {
+		width = 80
+	}
```
Comment (masaru-iritani) [inline internal/app/table_failed.go:121]: 96 is used for dividers. Should we use it here as well?

File: internal/app/table_failed.go [hunk 2]
```diff
@@ -2,12 +2,13 @@ package app
...
 	"fmt"
+	"os"
 	"sort"
 	"strings"
 
 	"github.com/charmbracelet/lipgloss"
-
 	"github.com/mfridman/tparse/parse"
+	"golang.org/x/term"
 )
```
Comment (ccoVeille) [inline internal/app/table_failed.go:12]: The classic blocks for ordering are

- std lib
- new line
- external dependencies
- new line
- subpackages of current module

So here, it should be

```go
 import ( 
          "fmt" 
          "os" 
          "sort" 
          "strings" 
 
          "github.com/charmbracelet/lipgloss" 
          "golang.org/x/term"

          "github.com/mfridman/tparse/parse" 
  )
```

Comment (masaru-iritani) [reply internal/app/table_failed.go]: Fixed by ce79ac6ade070362a86b6e7bbab8a544928135f2

File: internal/app/table_failed.go (hunk 1 above)
Comment (masaru-iritani) [reply internal/app/table_failed.go]: Tried using the terminal width (with a fallback to 96) for both panic messages and dividers in 4ee4e5e2cdce944de990992a27d047eebdf5c60f

**Review by ccoVeille — APPROVED** [review]

File: go.mod [hunk 3]
```diff
@@ -24,5 +24,6 @@ require (
 	github.com/rivo/uniseg v0.4.7 // indirect
 	github.com/xo/terminfo v0.0.0-20220910002029-abceb7e1c41e // indirect
 	golang.org/x/sys v0.33.0 // indirect
+	golang.org/x/term v0.32.0 // indirect
```
Comment (mfridman) [inline go.mod:27]: Run `go mod tidy`

**Review by mfridman — APPROVED** [review]
Thanks for the PR 🚀
